FROM node:22-alpine AS base
WORKDIR /app

FROM base AS deps
COPY package*.json .
RUN npm ci --omit=dev

FROM base AS build
COPY . .
RUN npm ci && npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=deps /app/node_modules /usr/share/nginx/html/node_modules

CMD ["nginx", "-g", "daemon off;"]

