apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-server-web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
      env: dev
  template:
    metadata:
      labels:
        app: frontend
        env: dev
    spec:
      containers:
        - name: container01
          image: python:3.7-alpine
          command: [
            "sh",
            "-c",
            "echo 'pagina desde python' > index.html && python -m http.server 8080"
          ]
---
apiVersion: v1
kind: Service
metadata:
  name: svc-python
spec:
  type: LoadBalancer
  selector:
    app: frontend
    env: dev
  ports:
    - port: 3000
      targetPort: 8080
      protocol: TCP
      name: port-web