apiVersion: v1
kind: Secret
metadata:
  name: parameters-dev
data:
  dbHost: aHR0cDovL2RiLm15Y29tcGFueS5jb20=
  dbPort: MzMwNg==
  dbUser: dXNlcg==
  dbPass: M2xHaWdhbnRlMjAyNT8=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-dev
  labels:
    env: dev
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      env: dev
  template:
    metadata:
      labels:
        app: frontend
        env: dev
    spec:
      containers:
        - name: container01
          image: nginx:alpine
          env:
            - name: TITLE
              value: "Frontend App"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: parameters-dev
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: parameters-dev
                  key: dbPort
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: parameters-dev
                  key: dbUser
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: parameters-dev
                  key: dbPass                                    