apiVersion: v1
kind: ConfigMap
metadata:
  name: parameters-dev
data:
  apiUrl: http://dev-api.mycompany.com
  domain: http://dev.mycompany.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-dev
  labels:
    env: dev
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      env: dev
  template:
    metadata:
      labels:
        app: frontend
        env: dev
    spec:
      containers:
        - name: container01
          image: nginx:alpine
          env:
            - name: TITLE
              value: "Frontend App"
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: parameters-dev
                  key: apiUrl
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: parameters-dev
                  key: domain